services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: team_tasks
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_backend
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DATABASE_URL: postgres://postgres:senha@postgres:5432/team_tasks
      RABBITMQ_URI: amqp://admin:admin@rabbitmq:5672
    ports:
      - "3000:3000"
    command: >
      sh -c "
        npm install &&
        npm run migration:run &&
        npm run start:prod
      "
  frontend:
    image: node:18
    container_name: frontend
    working_dir: /app
    ports:
      - "4200:4200"
    depends_on:
      - backend
    command: >
      sh -c "
        git clone https://github.com/henriSandovalSilva/team-task-manager-frontend.git . &&
        npm install &&
        npm run start -- --host 0.0.0.0
      "
volumes:
  pgdata:
